name: Build and Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ 'Release R20', 'Release R21', 'Release R22', 'Release R23', 'Release R24' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        run: NuGet/setup-nuget@v.1.0.2

      - name: Restore Nuget packages
        run: nuget restore AnlaxBase.sln

      - name: Build the Solution
        run: msbuild AnlaxBase.sln


