name: Build and Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ 'Release R20', 'Release R21', 'Release R22', 'Release R23', 'Release R24' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore  # ”бираем параметр --framework

      - name: Build project
        run: dotnet build --configuration ${{ matrix.configuration }} --framework net48  # ”казываем фреймворк только здесь

      - name: Publish output
        run: dotnet publish -c ${{ matrix.configuration }} --framework net48 -o ./output  # явно указываем фреймворк net48

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}-build
          path: ./output
