name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet dependencies with version
      run: dotnet restore AnlaxBase.sln /p:Configuration="Release R22" /p:AnlaxPackageVersion="2022.0.6"

    - name: Build the solution
      run: dotnet build AnlaxBase.sln --configuration "Release R22" /p:Platform="x64"

    - name: Upload AnlaxBase.dll as release asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'v1.2.2'  # Указание тега релиза
        name: AnlaxBase.dll
        files: ./bin/x64/Release\ R22/net48/AnlaxBase.dll
        token: ${{ secrets.ANLAXD }}
      env:
        GITHUB_TOKEN: ${{ secrets.ANLAXD }}