name: Build and Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ 'Release R22' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: dotnet restore AnlaxBase.sln /p:AnlaxPackageVersion="2022.0.6"

      - name: Build the Solution
        run: msbuild AnlaxBase.sln /p:Configuration="${{ matrix.configuration }}"

      - name: Publish output
        run: msbuild AnlaxBase.sln /p:Configuration="${{ matrix.configuration }}" /p:OutputPath=./output /p:DeployOnBuild=true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}-build
          path: ./output

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ANLAXD }}
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release ${{ github.run_number }}'
          body: |
            Автоматическая сборка и релиз для конфигурации: ${{ matrix.configuration }}.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ANLAXD }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output
          asset_name: ${{ matrix.configuration }}-release_build.zip
          asset_content_type: application/zip
