name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup NuGet
      run: nuget restore AnlaxBase.sln

    - name: Restore dependencies
      run: dotnet restore AnlaxBase.sln /p:AnlaxPackageVersion="2022.0.6"

    - name: Build the solution
      run: dotnet build AnlaxBase.sln --configuration "Release R22" /p:Platform="x64"

    - name: Create output directory
      run: mkdir output

    - name: Create zip file using PowerShell
      run: |
        Compress-Archive -Path ./bin/Release/* -DestinationPath ./output/release_build.zip
      shell: pwsh

    - name: Upload build as release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/release_build.zip
        asset_name: release_build.zip
        asset_content_type: application/zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false