name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup NuGet
      run: nuget restore AnlaxBase.sln

    - name: Restore dependencies
      run: dotnet restore AnlaxBase.sln /p:AnlaxPackageVersion="2022.0.6"

    - name: Build the solution
      run: dotnet build AnlaxBase.sln --configuration "Release R22" /p:Platform="x64"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ANLAXD }}
      with:
        tag_name: v1.1
        release_name: Release v1.1
        draft: false
        prerelease: false

    - name: Check current directory
      run: pwd

    - name: List files in bin directory
      run: ls -la ./bin

    - name: List files in Release directory
      run: ls -la "./bin/x64"

    - name: List files in Release R22 directory
      run: ls -la "./bin/x64/Release R22"

    - name: List files in net48 directory
      run: ls -la "./bin/x64/Release R22/net48"

    - name: Upload DLL as release asset
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./bin/x64/Release R22/net48/AnlaxBase.dll"
          asset_name: AnlaxBase.dll
          asset_content_type: application/octet-stream